# Generated by Django 4.1.4

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    # Initial migration for the app
    initial = True

    dependencies = [
        # No dependencies since this is the initial migration
    ]

    operations = [
        migrations.CreateModel(
            name='user_prompts_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Stores a unique identifier for the user's session
                ('session_id', models.TextField(default='')),
                # Represents the user ID associated with the prompt
                ('user_id', models.IntegerField(default=0)),
                # Stores the actual prompt submitted by the user
                ('user_prompt', models.TextField(default='')),
                # Timestamp indicating when the record was created
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='prompt_response_with_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Stores the model used for generating the response
                ('model', models.CharField(default='', max_length=256)),
                # Timestamp indicating when the response was created
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                # Foreign key linking this response to a specific user prompt
                ('user_prompts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LLM_chatting_app.user_prompts_record')),
            ],
        ),
    ]
