# Generated by Django 4.1.4

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        # Depends on the initial migration of the LLM_chatting_app
        ('LLM_chatting_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt_response_with_models',
            name='answer',
            # Adds a new field to store the generated response from the model
            field=models.TextField(default=''),
        ),
    ]
